/** Declaration file generated by dts-gen */
/* tslint:disable */

export = clone_deep;

declare function clone_deep(val: any, instanceClone?: any): any;

declare namespace clone_deep {
    const prototype: {
    };

}

