/** Declaration file generated by dts-gen */
/* tslint:disable */

export = fastify_cookie;

declare function fastify_cookie(fastify: any, options: any, next: any): void;

declare namespace fastify_cookie {
    const prototype: {
    };

}

