/** Declaration file generated by dts-gen */
/* tslint:disable */

export = mongoose_validator;

declare function mongoose_validator(options: any, ...args: any[]): any;

declare namespace mongoose_validator {
    const defaultErrorMessages: {
        contains: string;
        equals: string;
        isAfter: string;
        isAlpha: string;
        isAlphanumeric: string;
        isAscii: string;
        isBase64: string;
        isBefore: string;
        isBoolean: string;
        isByteLength: string;
        isCreditCard: string;
        isCurrency: string;
        isDataURI: string;
        isDecimal: string;
        isDivisibleBy: string;
        isEmail: string;
        isEmpty: string;
        isFQDN: string;
        isFloat: string;
        isFullWidth: string;
        isHalfWidth: string;
        isHexColor: string;
        isHexadecimal: string;
        isIP: string;
        isISBN: string;
        isISIN: string;
        isISO8601: string;
        isISSN: string;
        isIn: string;
        isInt: string;
        isJSON: string;
        isLength: string;
        isLowercase: string;
        isMACAddress: string;
        isMD5: string;
        isMobilePhone: string;
        isMongoId: string;
        isMultibyte: string;
        isNumeric: string;
        isSurrogatePair: string;
        isURL: string;
        isUUID: string;
        isUppercase: string;
        isVariableWidth: string;
        matches: string;
    };

    const prototype: {
    };

    function extend(name: any, fn: any, msg: any): any;

    namespace extend {
        const prototype: {
        };

    }

}

